<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfEditableComponentTable extends Doctrine_Table
{
  const 
    DEFAULT_NAMESPACE = 'default',
    DEFAULT_TYPE = 'html';
    
  static function updateComponent($name, $content, $type = null, $namespace = null)
  {
    $component = Doctrine::getTable('sfEditableComponent')->getEditableComponent($name, $type, $namespace);
    
    // FIXME: filter html content
    $component->setContent($content);
    
    $component->save();
  }
  
  static public function getEditableComponent($name, $type = null, $namespace = null, $createAndSave = true)
  {
    if (is_null($type))
    {
      $type = self::DEFAULT_TYPE;
    }
    
    if (is_null($namespace))
    {
      $namespace = self::DEFAULT_NAMESPACE;
    }
    
    $table = Doctrine::getTable('sfEditableComponent');
    
    $component = $table->createQuery('c')
      ->where('c.name = ? and c.type = ? and c.namespace = ?', array($name, $type, $namespace))
      ->fetchOne();
    
    if (!$component)
    {
      $component = $table->create(array(
        'name'      => $name,
        'type'      => $type,
        'namespace' => $namespace,
        'content'   => sfConfig::get(sprintf('app_sfDoctrineEditableComponentPlugin_default_content.%s', $type), 'Double-click to edit me!'),
      ));
      
      if (true === $createAndSave)
      {
        try
        {
          $component->save();
        }
        catch (Doctrine_Validator_Exception $e)
        {
          if (preg_match('/(unique)/', $e->getMessage()))
          {
            throw new RuntimeException(sprintf('A "%s" "%s" editable component in the "%s" namespace already exists in the database, and therefore connot be declared twice.', 
                                               $name, $type, $namespace));
          }
          
          throw $e;
        }
      }
    }
    
    return $component;
  }
}