<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfEditableComponentTable extends Doctrine_Table
{
  const 
    DEFAULT_NAMESPACE = 'default',
    DEFAULT_TYPE = 'html';
  
  /**
   * Updates a component
   *
   * @param  string       $name       The component name
   * @param  string       $content    The component content
   * @param  string|null  $type       The component type (html, plain) (optional)
   * @param  string|null  $namespace  The component namespace (optional)
   *
   * @return sfEditableComponent
   */
  static function updateComponent($name, $content, $type = null, $namespace = null)
  {
    $component = Doctrine::getTable('sfEditableComponent')->getComponent($name, $type, $namespace);
    
    // FIXME: filter html content
    $component->setContent($content);
    
    return $component->save();
  }
  
  /**
   * Retrieves or creates a component
   *
   * @param  string       $name           The component name
   * @param  string|null  $type           The component type (html, plain) (optional)
   * @param  string|null  $namespace      The component namespace (optional)
   * @param  Boolean      $createAndSave  Create a new record if component not found?
   *
   * @return sfEditableComponent
   */
  static public function getComponent($name, $type = null, $namespace = null, $createAndSave = true)
  {
    if (is_null($type))
    {
      $type = self::DEFAULT_TYPE;
    }
    
    if (is_null($namespace))
    {
      $namespace = self::DEFAULT_NAMESPACE;
    }
    
    $table = Doctrine::getTable('sfEditableComponent');
    
    $component = $table->createQuery('c')
      ->where('c.name = ? and c.type = ? and c.namespace = ?', array($name, $type, $namespace))
      ->fetchOne();
    
    if (!$component)
    {
      $component = $table->create(array(
        'name'      => $name,
        'type'      => $type,
        'namespace' => $namespace,
        'content'   => sfConfig::get(sprintf('app_sfDoctrineEditableComponentPlugin_default_content.%s', $type), 'Double-click to edit me!'),
      ));
      
      if (true === $createAndSave)
      {
        $component->save();
      }
    }
    
    return $component;
  }
}