<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfEditableComponentTable extends Doctrine_Table
{
  const DEFAULT_TYPE = 'html';
  
  /**
   * Updates a component
   *
   * @param  string       $name       The component name
   * @param  string       $content    The component content
   * @param  string|null  $type       The component type (html, plain) (optional)
   *
   * @return sfEditableComponent
   */
  static function updateComponent($name, $content, $type = self::DEFAULT_TYPE)
  {
    $component = self::getComponent($name, $type);
    
    $component->setContent($content);
    
    return $component->save();
  }
  
  /**
   * Retrieves or creates a component
   *
   * @param  string       $name           The component name
   * @param  string|null  $type           The component type (html, plain) (optional)
   * @param  Boolean      $createAndSave  Create a new record if component not found?
   *
   * @return sfEditableComponent
   */
  static public function getComponent($name, $type = self::DEFAULT_TYPE, $createAndSave = true)
  {
    $table = Doctrine::getTable('sfEditableComponent');
    
    $component = $table->createQuery('c')
      ->leftJoin('c.Translation ct INDEXBY ct.lang')
      ->where('c.name = ? and c.type = ?', array($name, $type))
      ->fetchOne()
    ;
    
    if (!$component instanceof sfEditableComponent && true === $createAndSave)
    {
      $component = $table->create(array(
        'name'      => $name,
        'type'      => $type,
        'content'   => sfConfig::get(sprintf('app_sfDoctrineEditableComponentPlugin_default_content.%s', $type), ''),
      ));
      
      $component->save();
    }
    
    return $component;
  }
}